#drivers/input/touchscreen/focaltech_ts/focaltech_test
#
# Makefile for test module
#
# Linux driver folder
obj-y += focaltech_test_ft5446.o
obj-y += focaltech_test_config_ft5446.o
obj-y += focaltech_test_supported_ic.o

